VodkaReview/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources:vodkas
  root 'vodkas#index'
end

VodkaReview/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :vodkas
  
  
end

VodkaReview/app/models/user.rb
class User < ActiveRecord::Base
  has_many :vodkas
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

VodkaReview/app/models/vodka.rb
class Vodka < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  
  validates_presence_of :name, :description, :origin
    validates :name, :length => { :minimum => 2 }
    validates :description, :length => { :minimum => 2 }
    validates :origin, presence: true, :length => { :minimum => 2 }
end

VodkaReview/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

VodkaReview/app/controllers/vodkas_controller.rb
class VodkasController < ApplicationController
  
  before_action :find_vodka, only: [:show, :edit, :update, :destroy]
    


  
  def index
    if params[:category].blank?
      @vodkas = Vodka.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @vodkas = Vodka.where(:category_id => @category_id).order("created_at DESC")
    end
    
    if params[:search]
				@vodkas = Vodka.search(params[:search]).paginate(:page => params[:page], :per_page => 5)
		else
      @vodkas = Vodka.paginate(:page => params[:page], :per_page => 5)
    end
  end
  
  
  def new
    @vodka = current_user.vodkas.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end
  
  def create
    @vodka = current_user.vodkas.build(vodka_params)
    @vodka.category_id = params[:category_id]
    if @vodka.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  
  
  def show
    
  end
  
  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end
  
  def update
    @vodka.category_id = params[:category_id]
    if @vodka.update(vodka_params)
      redirect_to vodka_path(@vodka)
    else
      render 'edit'
    end
  end
  
  def destroy
    @vodka.destroy
    redirect_to root_path
  end
  
  
  private
  
    def vodka_params
      params.require(:vodka).permit(:name, :description, :origin, :category_id, :vodka_img)
    end
  
  def find_vodka
     @vodka = Vodka.find(params[:id])
  end 
end

VodkaReview/app/helpers/application_helper.rb
module ApplicationHelper
end

VodkaReview/app/helpers/vodkas_helper.rb
module VodkasHelper
end

VodkaReview/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Base of Vodkas</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 
 <nav class="navbar navbar-default">
   
   <div class="container">
     
     <div class="navbar-header">
       <%= link_to "Base of Vodkas", root_path, class: "navbar-brand" %>
      
     </div>
     <ul class="nav navbar-nav">
       <li><%= link_to "Sign up", new_user_registration_path %></li>
       
       <% if user_signed_in? %>
        
         <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
         
       <% else %>
       
         <li><%= link_to "Log in", new_user_session_path %></li>
       
       <% end %>
     </ul>
     
     <ul class="nav navbar-nav navbar-right">
      
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Categories <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% Category.all.each do |category| %>
          <li class="<%= 'active' if params[:category] == category.name %>">
              <%= link_to category.name, vodkas_path(category: category.name), class: "link" %>
            </li>
          <% end %>
        </ul>
      </li>
       
      
       <% if user_signed_in? %>
         <li>  <%= link_to "Add vodka", new_vodka_path %> </li>
       <% end %>
     </ul>
     
   </div>
   
 </nav>
 
 
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <%= yield %>

</body>
</html>

VodkaReview/app/views/vodkas/_form.html.erb
<%= simple_form_for @vodka do |f| %>



  <% if @vodka.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vodka.errors.count, "error") %> :</h2>

      <ul>
      <% @vodka.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  
  <%= f.input :name, :required => true, :id => 'imie', :minimum => 5, label: "Name" %>
  <%= f.input :description,:required => true, :id => 'opis', :minimum => 5,  label: "Description" %>
  <%= f.input :origin, :required => true, :id => 'pochodzenie',:minimum => 5, label: "Origin" %>
  <%= f.button :submit , :id => 'sprawdz' %>
  
<% end %>

VodkaReview/app/views/vodkas/edit.html.erb
<div class="container">
    <h1>Edit Vodka</h1>

  <%= simple_form_for @vodka, :html => { :multipart => true } do |f| %>

  <% if @vodka.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vodka.errors.count, "error") %> :</h2>

      <ul>
      <% @vodka.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    

    <%= f.input :name,:required => true, label: "Name" %>
    <%= f.input :description,:required => true,  label: "Description" %>
    <%= f.input :origin,:required => true, label: "Origin" %>
    <%= f.button :submit  %>

  <% end %>
</div>

VodkaReview/app/views/vodkas/index.html.erb
 <div class="container">
   <h3 class="current-category"><%= params[:category] %></h3>

  <% if @vodkas.count == 0 %>

    <h2>There are no Vodkas in this category</h2>
  <% else %>
   <ul class="vodkasList">
    <% @vodkas.each do |vodka|%>

       <li><%= link_to vodka.name, vodka_path(vodka) %> </li>

       

    <% end %>
     <div class="text-center">
        <%= will_paginate @vodkas %>
    </div>
   </ul>
  <% end %>
</div>

VodkaReview/app/views/vodkas/new.html.erb
<div class="container">
  <h1>New Vodka</h1>


  <%= render 'form' %>
</div>

VodkaReview/app/views/vodkas/show.html.erb
<div class="container">
    <h2><%= @vodka.name %> </h2>
 


  <h3>Origin: <%= @vodka.origin %> </h3>
  <p>Description: <%= @vodka.description %> </p>




  <%= link_to "Back", root_path %>

  <% if user_signed_in? %>


    <% if @vodka.user.id == current_user.id %>

      <%= link_to "Edit", edit_vodka_path(@vodka) %>
      <%= link_to "Delete", vodka_path(@vodka), method: :delete, data: { confirm: "Are you sure?" } %>

    <% end %>

  <% end %>
</div>